language: objective-c
osx_image: xcode12
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator14.0
script:
  - xcodebuild -showsdks
  - xcodebuild -project UIRating/UIRating.xcodeproj -scheme 'UIRating' -sdk $IOS_SDK build analyze
